/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import javax.swing.JOptionPane;
import modelo.*;
/**
 *
 * @author Giu
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_P_NomeCliente = new javax.swing.JTextField();
        jTextField_P_NumeroConta = new javax.swing.JTextField();
        jTextField_P_DiaRendimento = new javax.swing.JTextField();
        jTextField_P_Saldo = new javax.swing.JTextField();
        jTextField_P_Depositar = new javax.swing.JTextField();
        jTextField_P_Sacar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_P_Resultado = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_B_NomeCliente = new javax.swing.JTextField();
        jTextField_B_NumeroConta = new javax.swing.JTextField();
        jTextField_B_Saldo = new javax.swing.JTextField();
        jTextField_B_Depositar = new javax.swing.JTextField();
        jTextField_B_Sacar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_B_Resultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_L_NomeCliente = new javax.swing.JTextField();
        jTextField_L_NumeroConta = new javax.swing.JTextField();
        jTextField_L_Limite = new javax.swing.JTextField();
        jTextField_L_Saldo = new javax.swing.JTextField();
        jTextField_L_Depositar = new javax.swing.JTextField();
        jTextField_L_Sacar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_L_Resultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Conta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selecione um tipo de Conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(240, 239, 239));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setText("Nome do Cliente");

        jLabel7.setText("Número da Conta");

        jLabel8.setText("Saldo");

        jLabel9.setText("Depositar");

        jLabel10.setText("Sacar");

        jLabel11.setText("Dia do Rendimento");

        jLabel20.setText("R$");

        jLabel21.setText("R$");

        jLabel22.setText("R$");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextArea_P_Resultado.setEditable(false);
        jTextArea_P_Resultado.setBackground(new java.awt.Color(240, 239, 239));
        jTextArea_P_Resultado.setColumns(20);
        jTextArea_P_Resultado.setRows(5);
        jScrollPane1.setViewportView(jTextArea_P_Resultado);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_P_NomeCliente)
                    .addComponent(jTextField_P_NumeroConta)
                    .addComponent(jTextField_P_DiaRendimento)
                    .addComponent(jTextField_P_Saldo)
                    .addComponent(jTextField_P_Depositar)
                    .addComponent(jTextField_P_Sacar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_P_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_P_DiaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_P_NumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_P_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_P_Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_P_Sacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conta Poupança          ", jPanel2);

        jLabel5.setText("Sacar");

        jLabel4.setText("Depositar");

        jLabel3.setText("Saldo");

        jLabel2.setText("Número da Conta");

        jLabel1.setText("Nome do Cliente");

        jLabel23.setText("R$");

        jLabel24.setText("R$");

        jLabel25.setText("R$");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextArea_B_Resultado.setBackground(new java.awt.Color(240, 239, 239));
        jTextArea_B_Resultado.setColumns(20);
        jTextArea_B_Resultado.setRows(5);
        jScrollPane2.setViewportView(jTextArea_B_Resultado);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_B_NomeCliente)
                    .addComponent(jTextField_B_NumeroConta)
                    .addComponent(jTextField_B_Saldo)
                    .addComponent(jTextField_B_Depositar)
                    .addComponent(jTextField_B_Sacar, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_B_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_B_NumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_B_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_B_Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_B_Sacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Conta Corrente Básica          ", jPanel3);

        jLabel12.setText("Nome do Cliente");

        jLabel13.setText("Número da Conta");

        jLabel14.setText("Saldo");

        jLabel15.setText("Depositar");

        jLabel16.setText("Sacar");

        jLabel17.setText("Limite");

        jLabel26.setText("R$");

        jLabel27.setText("R$");

        jLabel28.setText("R$");

        jLabel29.setText("R$");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Inseridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextArea_L_Resultado.setBackground(new java.awt.Color(240, 239, 239));
        jTextArea_L_Resultado.setColumns(20);
        jTextArea_L_Resultado.setRows(5);
        jScrollPane3.setViewportView(jTextArea_L_Resultado);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_L_NomeCliente)
                    .addComponent(jTextField_L_NumeroConta)
                    .addComponent(jTextField_L_Limite)
                    .addComponent(jTextField_L_Saldo)
                    .addComponent(jTextField_L_Depositar)
                    .addComponent(jTextField_L_Sacar, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_L_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_L_NumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField_L_Limite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_L_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_L_Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_L_Sacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Conta Corrente com Limite          ", jPanel4);

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Apagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
           Conta_Poupanca dados_conta_poupanca = new Conta_Poupanca();
           Conta_Corrente_Basica dados_conta_corrente = new Conta_Corrente_Basica();
           Conta_Corrente_Limite dados_conta_corrente_limite = new Conta_Corrente_Limite();
           
           String entrada = "";
           
           if (jTextField_B_NomeCliente.getText().equals("") && 
               jTextField_L_NomeCliente.getText().equals("")) {
           
           //nome
           entrada = jTextField_P_NomeCliente.getText();
           dados_conta_poupanca.setNome_cliente(entrada);
           //numero da conta
           entrada = jTextField_P_NumeroConta.getText();
           dados_conta_poupanca.setNumero_conta(Integer.parseInt(entrada));
           //dia do rendimento
           entrada = jTextField_P_DiaRendimento.getText();
           dados_conta_poupanca.setDia_rendimento_dinheiro(Integer.parseInt(entrada));
           //saldo
           entrada = jTextField_P_Saldo.getText();
           dados_conta_poupanca.setSaldo(Float.parseFloat(entrada));
           //depositar
           entrada = jTextField_P_Depositar.getText();
           dados_conta_poupanca.depositar(Float.parseFloat(entrada));
           //sacar
           entrada = jTextField_P_Sacar.getText();
           dados_conta_poupanca.sacar(Float.parseFloat(entrada));
           //novo saldo
           
           
           String saida_dados_conta_poupanca = "\nDados da Conta \n\n";
           saida_dados_conta_poupanca += "Tipo: " + dados_conta_poupanca.getTipoDaConta() +"\n";
           saida_dados_conta_poupanca += "Nome do Cliente: " + dados_conta_poupanca.getNome_cliente()+ "\n";
           saida_dados_conta_poupanca += "Número da Conta: " + dados_conta_poupanca.getNumero_conta()+ "\n";
           saida_dados_conta_poupanca += "Dia do Rendimendo: " + dados_conta_poupanca.getDia_rendimento_dinheiro()+ "\n";
           saida_dados_conta_poupanca += "O Rendimento foi Calculado?: " + dados_conta_poupanca.calcularNovoSaldo(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_poupanca += "Taxa do Rendimento: " + dados_conta_poupanca.calcularNovoSaldoValor(ERROR)+ "\n";
           //saida_dados_conta_poupanca += "Fez algum Depósito?: " + dados_conta_poupanca.depositar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_poupanca += "Saldo: " + jTextField_P_Saldo.getText() + "\n";
           saida_dados_conta_poupanca += "Valor do Depósito: " + jTextField_P_Depositar.getText() + "\n";
           //saida_dados_conta_poupanca += "Fez algum Saque?: " + dados_conta_poupanca.sacar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_poupanca += "Valor do Saque: " + jTextField_P_Sacar.getText() + "\n";
           saida_dados_conta_poupanca += "\nSaldo Final: " + dados_conta_poupanca.getSaldo()+ "\n";
           
           jTextArea_P_Resultado.setText(saida_dados_conta_poupanca);
           }
           else if (jTextField_P_NomeCliente.getText().equals("") && 
               jTextField_L_NomeCliente.getText().equals("")) {
           
           /*****************************************************/
           /*****************************************************/
           
           //nome
           entrada = jTextField_B_NomeCliente.getText();
           dados_conta_corrente.setNome_cliente(entrada);
           //numero da conta
           entrada = jTextField_B_NumeroConta.getText();
           dados_conta_corrente.setNumero_conta(Integer.parseInt(entrada));
           //saldo
           entrada = jTextField_B_Saldo.getText();
           dados_conta_corrente.setSaldo(Float.parseFloat(entrada));
           //depositar
           entrada = jTextField_B_Depositar.getText();
           dados_conta_corrente.depositar(Float.parseFloat(entrada));
           //sacar
           entrada = jTextField_B_Sacar.getText();
           dados_conta_corrente.sacar(Float.parseFloat(entrada));
           //novo saldo
           
           
           /*
           String saida_dados_conta_corrente = "\nDados da Conta \n\n";
           saida_dados_conta_corrente += "Tipo: " + dados_conta_corrente.getTipoDaConta() +"\n";
           saida_dados_conta_corrente += "Nome do Cliente: " + dados_conta_corrente.getNome_cliente()+ "\n";
           saida_dados_conta_corrente += "Número da Conta: " + dados_conta_corrente.getNumero_conta()+ "\n";
           saida_dados_conta_corrente += "Saldo: " + dados_conta_corrente.getSaldo()+ "\n";
           //saida_dados_conta_corrente += "Depositar: " + dados_conta_corrente.depositar(ERROR) + "\n";
           saida_dados_conta_corrente += "Sacar: " + dados_conta_corrente.sacar(TOP_ALIGNMENT) + "\n";
           */
           String saida_dados_conta_corrente = "\nDados da Conta \n\n";
           saida_dados_conta_corrente += "Tipo: " + dados_conta_corrente.getTipoDaConta() +"\n";
           saida_dados_conta_corrente += "Nome do Cliente: " + dados_conta_corrente.getNome_cliente()+ "\n";
           saida_dados_conta_corrente += "Número da Conta: " + dados_conta_corrente.getNumero_conta()+ "\n";
           //saida_dados_conta_corrente += "Fez algum Depósito?: " + dados_conta_corrente.depositar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_corrente += "Saldo: " + jTextField_B_Saldo.getText() + "\n";
           saida_dados_conta_corrente += "Valor do Depósito: " + jTextField_B_Depositar.getText() + "\n";
           //saida_dados_conta_poupanca += "Fez algum Saque?: " + dados_conta_corrente.sacar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_corrente += "Valor do Saque: " + jTextField_B_Sacar.getText() + "\n";
           saida_dados_conta_corrente += "\nSaldo Final: " + dados_conta_corrente.getSaldo()+ "\n";
           
           jTextArea_B_Resultado.setText(saida_dados_conta_corrente);
           
           }
           
           /*****************************************************/
           /*****************************************************/
        
           
           if (jTextField_B_NomeCliente.getText().equals("") && 
               jTextField_P_NomeCliente.getText().equals("")) {
               
           
           //nome
           entrada = jTextField_L_NomeCliente.getText();
           dados_conta_corrente_limite.setNome_cliente(entrada);
           //numero da conta
           entrada = jTextField_L_NumeroConta.getText();
           dados_conta_corrente_limite.setNumero_conta(Integer.parseInt(entrada));
           //limite
           entrada = jTextField_L_Limite.getText();
           dados_conta_corrente_limite.setConta_limite(Float.parseFloat(entrada));
           //saldo
           entrada = jTextField_L_Saldo.getText();
           dados_conta_corrente_limite.setSaldo(Float.parseFloat(entrada));
           //depositar
           entrada = jTextField_L_Depositar.getText();
           dados_conta_corrente_limite.depositar(Float.parseFloat(entrada));
           //sacar
           entrada = jTextField_L_Sacar.getText();
           dados_conta_corrente_limite.sacar(Float.parseFloat(entrada));
           //novo saldo
           
           /*
           String saida_dados_conta_corrente_limite = "\nDados da Conta \n\n";
           saida_dados_conta_corrente_limite += "Tipo: " + dados_conta_corrente_limite.getTipoDaConta() +"\n";
           saida_dados_conta_corrente_limite += "Nome do Cliente: " + dados_conta_corrente_limite.getNome_cliente()+ "\n";
           saida_dados_conta_corrente_limite += "Número da Conta: " + dados_conta_corrente_limite.getNumero_conta()+ "\n";
           //saida_dados_conta_corrente_limite += "Limite: " + dados_conta_corrente_limite.setConta_limite(ALLBITS) + "\n";
           saida_dados_conta_corrente_limite += "Saldo: " + dados_conta_corrente_limite.getSaldo()+ "\n";
           //saida_dados_conta_corrente_limite += "Depositar: " + dados_conta_corrente_limite.depositar(ERROR) + "\n";
           saida_dados_conta_corrente_limite += "Sacar: " + dados_conta_corrente_limite.sacar(TOP_ALIGNMENT) + "\n";
           */
           
           String saida_dados_conta_corrente_limite = "\nDados da Conta \n\n";
           saida_dados_conta_corrente_limite += "Tipo: " + dados_conta_corrente_limite.getTipoDaConta() +"\n";
           saida_dados_conta_corrente_limite += "Nome do Cliente: " + dados_conta_corrente_limite.getNome_cliente()+ "\n";
           saida_dados_conta_corrente_limite += "Número da Conta: " + dados_conta_corrente_limite.getNumero_conta()+ "\n";
           //saida_dados_conta_corrente_limite += "Fez algum Depósito?: " + dados_conta_corrente_limite.depositar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_corrente_limite += "Limite: " + jTextField_L_Limite.getText() + "\n";
           saida_dados_conta_corrente_limite += "Saldo: " + jTextField_L_Saldo.getText() + "\n";
           saida_dados_conta_corrente_limite += "Valor do Depósito: " + jTextField_L_Depositar.getText() + "\n";
           //saida_dados_conta_corrente_limite += "Fez algum Saque?: " + dados_conta_corrente_limite.sacar(TOP_ALIGNMENT) + "\n";
           saida_dados_conta_corrente_limite += "Valor do Saque: " + jTextField_L_Sacar.getText() + "\n";
           saida_dados_conta_corrente_limite += "\nSaldo Final: " + dados_conta_corrente_limite.getSaldo()+ "\n";
           
           jTextArea_L_Resultado.setText(saida_dados_conta_corrente_limite);
            
           }
            
            
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField_B_NomeCliente.setText("");
        jTextField_L_NomeCliente.setText("");
        jTextField_P_NomeCliente.setText("");
        
        jTextField_B_NumeroConta.setText("");
        jTextField_L_NumeroConta.setText("");
        jTextField_P_NumeroConta.setText("");
        
        jTextField_B_Saldo.setText("");
        jTextField_L_Saldo.setText("");
        jTextField_P_Saldo.setText("");
        
        jTextField_B_Depositar.setText("");
        jTextField_L_Depositar.setText("");
        jTextField_P_Depositar.setText("");
        
        jTextField_B_Sacar.setText("");
        jTextField_L_Sacar.setText("");
        jTextField_P_Sacar.setText("");
        
        jTextField_B_NomeCliente.setText("");
        jTextField_L_NomeCliente.setText("");
        jTextField_P_NomeCliente.setText("");
        
        jTextArea_L_Resultado.setText("");
        jTextArea_B_Resultado.setText("");
        jTextArea_P_Resultado.setText("");
        
        jTextField_L_Limite.setText("");
        
        jTextField_P_DiaRendimento.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_B_Resultado;
    private javax.swing.JTextArea jTextArea_L_Resultado;
    private javax.swing.JTextArea jTextArea_P_Resultado;
    private javax.swing.JTextField jTextField_B_Depositar;
    private javax.swing.JTextField jTextField_B_NomeCliente;
    private javax.swing.JTextField jTextField_B_NumeroConta;
    private javax.swing.JTextField jTextField_B_Sacar;
    private javax.swing.JTextField jTextField_B_Saldo;
    private javax.swing.JTextField jTextField_L_Depositar;
    private javax.swing.JTextField jTextField_L_Limite;
    private javax.swing.JTextField jTextField_L_NomeCliente;
    private javax.swing.JTextField jTextField_L_NumeroConta;
    private javax.swing.JTextField jTextField_L_Sacar;
    private javax.swing.JTextField jTextField_L_Saldo;
    private javax.swing.JTextField jTextField_P_Depositar;
    private javax.swing.JTextField jTextField_P_DiaRendimento;
    private javax.swing.JTextField jTextField_P_NomeCliente;
    private javax.swing.JTextField jTextField_P_NumeroConta;
    private javax.swing.JTextField jTextField_P_Sacar;
    private javax.swing.JTextField jTextField_P_Saldo;
    // End of variables declaration//GEN-END:variables
}
